[project]
name = "pranavi-hello"
version = "0.1.0"
description = "A hello world package with CLI using Typer and Rich"
requires-python = ">=3.8"
dependencies = [
    "typer[all]",
    "rich"
]

[project.scripts]
pranavi-hello = "pranavi_hello.cli:app"
